version: "3.8"

services:
  profile:
    container_name: "profile"
    build: 
      context: ./ethydev-kethy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      ./envs/.env.dev.profile
    
  lynx:
    container_name: "lynx"
    build:
      context: ./ethydev-lynx
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - shorty
    env_file:
      ./envs/.env.dev.lynx

  shorty:
    container_name: "shorty"
    build: 
      context: ./ethydev-api/shorty
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      ./envs/.env.dev.shorty

  postgres:
    container_name: "postgres"
    image: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/shorty/:/var/lib/postgresql/data
    env_file:
      ./envs/.env.dev.postgres
